# Generated by Django 5.2.17 on 2026-08-05 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evangelistic_headline', models.CharField(default='Boas-novas para Santa Leopoldina', max_length=200, verbose_name='Título evangelístico')),
                ('evangelistic_message', models.TextField(default='A Igreja Batista em Santa Leopoldina anuncia a Palavra de Deus e convida você a participar dos cultos.', verbose_name='Mensagem da home')),
                ('next_service_label', models.CharField(default='Próximo culto', max_length=120, verbose_name='Nome do próximo culto')),
                ('next_service_when', models.CharField(default='Consulte os horários', max_length=120, verbose_name='Quando é o próximo culto')),
                ('next_service_description', models.TextField(blank=True, default='Venha participar conosco.', verbose_name='Detalhes do próximo culto')),
                ('service_times', models.TextField(default='Domingo às 19h', verbose_name='Horários de culto')),
                ('address_line', models.CharField(default='Santa Leopoldina - ES', max_length=255, verbose_name='Endereço')),
                ('address_references', models.TextField(blank=True, default='', verbose_name='Pontos de referência')),
                ('map_url', models.URLField(blank=True, default='', help_text='Preferir link externo leve (Google Maps / OSM), sem incorporação pesada.', verbose_name='Link do mapa')),
                ('accessibility_info', models.TextField(blank=True, default='', verbose_name='Acessibilidade')),
                ('transport_info', models.TextField(blank=True, default='', help_text='Inclua orientações para visitantes da zona rural.', verbose_name='Transporte e caronas')),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='Ex.: 5527999999999', max_length=20, verbose_name='WhatsApp (somente dígitos, com DDI)')),
                ('whatsapp_default_message', models.CharField(default='Olá, gostaria de conversar com a igreja', max_length=300, verbose_name='Mensagem inicial do WhatsApp')),
                ('whatsapp_welcome_text', models.TextField(default='Fale conosco pelo WhatsApp para dúvidas, conversa, desabafo ou pedido de oração. Responderemos assim que possível — não é um canal de plantão 24 horas.', verbose_name='Texto de acolhimento do WhatsApp')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Configurações da igreja',
            },
        ),
    ]
