# Generated by Django 5.2.17 on 2026-08-05 06:11

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, default='', help_text='Frase curta exibida abaixo do título.', max_length=300, verbose_name='Resumo')),
                ('body', wagtail.fields.RichTextField(verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Página institucional',
                'verbose_name_plural': 'Páginas institucionais',
            },
            bases=('wagtailcore.page',),
        ),
    ]
