# Generated by Django 5.2.17 on 2026-08-10 13:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_news_pages'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, default='', max_length=300, verbose_name='Resumo')),
            ],
            options={
                'verbose_name': 'Índice da agenda',
                'verbose_name_plural': 'Índices da agenda',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('starts_at', models.DateTimeField(verbose_name='Início')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='Local')),
                ('body', wagtail.fields.RichTextField(blank=True, default='', verbose_name='Descrição')),
                ('requires_registration', models.BooleanField(default=False, verbose_name='Exige inscrição')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
            bases=('wagtailcore.page',),
        ),
    ]
