# Generated by Django 5.2.17 on 2026-08-10 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_event_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='confirmed', max_length=20, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='public.eventpage', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Inscrição em evento',
                'verbose_name_plural': 'Inscrições em eventos',
                'ordering': ['-created_at'],
            },
        ),
    ]
