# Generated by Django 5.2.17 on 2026-08-10 14:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_event_registration'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStreamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, default='', max_length=300, verbose_name='Resumo')),
                ('body', wagtail.fields.RichTextField(blank=True, default='', verbose_name='Conteúdo')),
                ('youtube_url', models.URLField(blank=True, default='', help_text='Link do vídeo ou transmissão no YouTube. Sem autoplay agressivo.', verbose_name='URL do YouTube ao vivo')),
            ],
            options={
                'verbose_name': 'Transmissão ao vivo',
                'verbose_name_plural': 'Transmissões ao vivo',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SermonIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, default='', max_length=300, verbose_name='Resumo')),
            ],
            options={
                'verbose_name': 'Índice de sermões',
                'verbose_name_plural': 'Índices de sermões',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SermonPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, default='', max_length=300, verbose_name='Resumo')),
                ('body', wagtail.fields.RichTextField(blank=True, default='', verbose_name='Conteúdo')),
                ('media_url', models.URLField(blank=True, default='', help_text='YouTube ou outro link externo. Não use upload de vídeo no portal.', verbose_name='URL da mídia incorporada')),
            ],
            options={
                'verbose_name': 'Sermão',
                'verbose_name_plural': 'Sermões',
            },
            bases=('wagtailcore.page',),
        ),
    ]
