# Generated by Django 5.2.17 on 2026-08-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0006_sermon_and_live_pages"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowChurchContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nome")),
                (
                    "email",
                    models.EmailField(blank=True, default="", max_length=254, verbose_name="E-mail"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, default="", max_length=30, verbose_name="Telefone"),
                ),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="Mensagem"),
                ),
                ("lgpd_consent", models.BooleanField(verbose_name="Consentimento LGPD")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Novo"),
                            ("in_progress", "Em acompanhamento"),
                            ("done", "Concluído"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contato Quero conhecer",
                "verbose_name_plural": "Contatos Quero conhecer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrayerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False, verbose_name="Anônimo")),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=120, verbose_name="Nome"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, default="", max_length=254, verbose_name="E-mail"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, default="", max_length=30, verbose_name="Telefone"),
                ),
                ("body", models.TextField(verbose_name="Pedido")),
                (
                    "lgpd_consent",
                    models.BooleanField(default=False, verbose_name="Consentimento LGPD"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Novo"),
                            ("in_progress", "Em acompanhamento"),
                            ("done", "Concluído"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pedido de oração",
                "verbose_name_plural": "Pedidos de oração",
                "ordering": ["-created_at"],
            },
        ),
    ]
