# Generated by Django 5.2.17 on 2026-08-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0007_prayer_and_know_church"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchsettings",
            name="facebook_url",
            field=models.URLField(blank=True, default="", verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="churchsettings",
            name="instagram_url",
            field=models.URLField(blank=True, default="", verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="churchsettings",
            name="pix_beneficiary_name",
            field=models.CharField(
                blank=True, default="", max_length=140, verbose_name="Nome do favorecido"
            ),
        ),
        migrations.AddField(
            model_name="churchsettings",
            name="pix_city",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Cidade do PIX"
            ),
        ),
        migrations.AddField(
            model_name="churchsettings",
            name="pix_instructions",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Texto público. O portal não processa pagamento nem guarda dados do doador.",
                verbose_name="Orientação para ofertas",
            ),
        ),
        migrations.AddField(
            model_name="churchsettings",
            name="pix_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Chave PIX da igreja. Não cadastre dados bancários de terceiros.",
                max_length=140,
                verbose_name="Chave PIX",
            ),
        ),
        migrations.AddField(
            model_name="churchsettings",
            name="pix_key_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("random", "Chave aleatória"),
                    ("email", "E-mail"),
                    ("phone", "Telefone"),
                    ("cpf", "CPF"),
                    ("cnpj", "CNPJ"),
                ],
                default="",
                max_length=20,
                verbose_name="Tipo da chave PIX",
            ),
        ),
        migrations.AddField(
            model_name="churchsettings",
            name="youtube_url",
            field=models.URLField(blank=True, default="", verbose_name="YouTube"),
        ),
    ]
