# Generated by Django 5.2.17 on 2026-08-22 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_pix_and_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Conta pessoas (titular + familiares). Sem valor, não há lista de espera.', null=True, verbose_name='Vagas'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='is_retreat',
            field=models.BooleanField(default=False, help_text='Usa inscrição familiar, transporte, PIX e check-in na área privada.', verbose_name='É retiro'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='sensitive_retain_days',
            field=models.PositiveIntegerField(default=30, help_text='Após o término do retiro, dados médicos e de menores são descartados.', verbose_name='Dias para descarte de dados sensíveis'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='accommodation',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Acomodação'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='boarding_point',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Ponto de embarque'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='dietary_restrictions',
            field=models.TextField(blank=True, default='', verbose_name='Restrições alimentares'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='emergency_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Contato de emergência'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone de emergência'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='guardian_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Responsável legal'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='guardian_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone do responsável'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='guardian_relationship',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Parentesco do responsável'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='is_minor',
            field=models.BooleanField(default=False, verbose_name='Menor de idade'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='lgpd_consent',
            field=models.BooleanField(default=False, verbose_name='Consentimento LGPD'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='medical_notes',
            field=models.TextField(blank=True, default='', verbose_name='Informações médicas'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='pix_status',
            field=models.CharField(blank=True, choices=[('pending', 'PIX pendente'), ('paid', 'PIX pago'), ('waived', 'Isento')], default='', max_length=20, verbose_name='Status do PIX'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='sensitive_discarded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dados sensíveis descartados em'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='transport_needed',
            field=models.BooleanField(default=False, verbose_name='Precisa de transporte'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmada'), ('waitlisted', 'Lista de espera'), ('cancelled', 'Cancelada')], default='confirmed', max_length=20, verbose_name='Situação'),
        ),
        migrations.CreateModel(
            name='EventFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('is_minor', models.BooleanField(default=False, verbose_name='Menor de idade')),
                ('dietary_restrictions', models.TextField(blank=True, default='', verbose_name='Restrições alimentares')),
                ('medical_notes', models.TextField(blank=True, default='', verbose_name='Informações médicas')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Check-in')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='public.eventregistration', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Familiar inscrito',
                'verbose_name_plural': 'Familiares inscritos',
                'ordering': ['name'],
            },
        ),
    ]
