# Generated by Django 5.2.17 on 2026-08-23 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_retreats'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='Token de acesso')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('refreshed_at', models.DateTimeField(blank=True, null=True, verbose_name='Renovado em')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização')),
                ('last_sync_error', models.TextField(blank=True, default='', verbose_name='Último erro de sincronização')),
            ],
            options={
                'verbose_name': 'Credencial do Instagram',
                'verbose_name_plural': 'Credenciais do Instagram',
            },
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='archive_frame_count',
            field=models.PositiveSmallIntegerField(default=12, help_text='Quantas fotografias a folha de contato exibe.', verbose_name='Quadros no acervo da home'),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='instagram_handle',
            field=models.CharField(blank=True, default='', help_text='Sem o @. Ex.: igrejabatista.santaleopoldina', max_length=60, verbose_name='Arroba do Instagram'),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='instagram_mode',
            field=models.CharField(choices=[('off', 'Desligado — usar apenas a galeria curada'), ('instagram_login', 'Login Empresarial do Instagram (conta Criador ou Empresa, sem Página)'), ('facebook_login', 'Login do Facebook (conta Empresa ligada a uma Página)')], default='off', help_text='A API oficial exige conta Profissional (Criador ou Empresa). Conta pessoal não tem acesso a nenhuma API oficial.', max_length=20, verbose_name='Origem do acervo'),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='instagram_user_id',
            field=models.CharField(blank=True, default='', help_text='Necessário apenas no Login do Facebook. O token é cadastrado fora desta tela.', max_length=40, verbose_name='ID da conta do Instagram'),
        ),
        migrations.CreateModel(
            name='ArchiveFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('curated', 'Curado no CMS')], default='curated', max_length=20, verbose_name='Origem')),
                ('remote_id', models.CharField(blank=True, default='', help_text='Preenchido pela sincronização. Deixe vazio em quadros curados.', max_length=80, verbose_name='ID no Instagram')),
                ('image', models.ImageField(upload_to='archive/', verbose_name='Fotografia')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Descreva a cena. Sem isso a fotografia fica inacessível.', max_length=250, verbose_name='Descrição para leitor de tela')),
                ('caption', models.CharField(blank=True, default='', help_text='Legenda curta, escrita como anotação a nanquim sob o quadro.', max_length=120, verbose_name='Legenda')),
                ('permalink', models.URLField(blank=True, default='', verbose_name='Link do post')),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Exibir no site')),
            ],
            options={
                'verbose_name': 'Quadro do acervo',
                'verbose_name_plural': 'Quadros do acervo',
                'ordering': ['-taken_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source', 'instagram')), fields=('remote_id',), name='unique_instagram_remote_id')],
            },
        ),
    ]
