# Generated by Django 5.2.17 on 2026-09-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0012_instagram_frames_2026_09"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveframe",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="Só vale para fotografia. Sem destaque, a abertura usa a fotografia mais recente.",
                verbose_name="Destaque na abertura",
            ),
        ),
        migrations.AddField(
            model_name="archiveframe",
            name="kind",
            field=models.CharField(
                choices=[("photo", "Fotografia"), ("art", "Arte ou cartaz")],
                default="photo",
                help_text="Fotografia entra na abertura e em “A vida em comunidade”. Arte ou cartaz (imagem com texto) vai inteira para o Mural, sem recorte.",
                max_length=10,
                verbose_name="Tipo",
            ),
        ),
    ]
