# Generated by Django 5.2.17 on 2026-09-27 19:31

from django.db import migrations, models

HEADLINE = "Um lugar para viver a fé. Uma família para caminhar com você."
MESSAGE = (
    "Em Cristo encontramos esperança, amor e uma comunidade onde podemos crescer juntos. "
    "Venha conhecer a Palavra de Deus, compartilhar a vida e fazer parte da nossa família."
)
REFERENCE = "Inspirado em Mateus 11:28 e Atos 2:42-47."


def use_new_welcome_text(apps, schema_editor):
    """Texto da abertura pedido pelo usuário em 27/09/2026; segue editável no CMS."""
    ChurchSettings = apps.get_model("public", "ChurchSettings")
    ChurchSettings.objects.update(
        evangelistic_headline=HEADLINE,
        evangelistic_message=MESSAGE,
        evangelistic_reference=REFERENCE,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0014_instagram_frames_2026_09_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchsettings",
            name="evangelistic_reference",
            field=models.CharField(
                blank=True,
                default="Inspirado em Mateus 11:28 e Atos 2:42-47.",
                help_text="Aparece discreta abaixo dos botões da abertura. Deixe vazio para ocultar.",
                max_length=200,
                verbose_name="Referência bíblica da mensagem",
            ),
        ),
        migrations.AlterField(
            model_name="churchsettings",
            name="evangelistic_headline",
            field=models.CharField(
                default="Um lugar para viver a fé. Uma família para caminhar com você.",
                help_text="Com duas frases, a segunda aparece em outra linha, em itálico vinho.",
                max_length=200,
                verbose_name="Título evangelístico",
            ),
        ),
        migrations.AlterField(
            model_name="churchsettings",
            name="evangelistic_message",
            field=models.TextField(
                default="Em Cristo encontramos esperança, amor e uma comunidade onde podemos crescer juntos. Venha conhecer a Palavra de Deus, compartilhar a vida e fazer parte da nossa família.",
                verbose_name="Mensagem da home",
            ),
        ),
        migrations.RunPython(use_new_welcome_text, migrations.RunPython.noop),
    ]
