# Generated by Django 5.2.17 on 2026-10-01 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0017_archiveframe_focal_point_full_frames"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional. Aparece como miniatura na lista e no topo da página.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagem de capa",
            ),
        ),
        migrations.AddField(
            model_name="newspage",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional. Aparece como miniatura na lista e no topo da página.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagem de capa",
            ),
        ),
        migrations.AddField(
            model_name="sermonpage",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional. Aparece como miniatura na lista e no topo da página.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagem de capa",
            ),
        ),
    ]
