# Generated by Django 5.2.17 on 2026-10-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0018_cover_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Nome")),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        verbose_name="Dia da semana",
                    ),
                ),
                (
                    "starts_at",
                    models.TimeField(
                        help_text="Horário de Brasília.", verbose_name="Horário"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Local"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="Descrição curta",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para tirar da agenda sem apagar.",
                        verbose_name="Aparece na agenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encontro semanal",
                "verbose_name_plural": "Encontros semanais",
                "ordering": ["weekday", "starts_at", "title"],
            },
        ),
    ]
