# Generated by Django 5.2.17 on 2026-08-15 05:05

import apps.private_area.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('audience', models.CharField(choices=[('members', 'Todos os membros'), ('content', 'Comunicação e pastor'), ('finances', 'Tesouraria'), ('admin', 'Administração')], default='members', max_length=32, verbose_name='Quem pode ver')),
                ('file', models.FileField(storage=apps.private_area.storage.private_document_storage, upload_to='documents/', verbose_name='Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_private_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento privado',
                'verbose_name_plural': 'Documentos privados',
                'ordering': ['-created_at'],
            },
        ),
    ]
