# Generated by Django 5.2.17 on 2026-08-20 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_area', '0002_ministry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='private_area.ministry')),
            ],
            options={
                'verbose_name': 'Escala mensal',
                'verbose_name_plural': 'Escalas mensais',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='Data e horário')),
                ('function', models.CharField(max_length=80, verbose_name='Função')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('declined', 'Recusado')], default='pending', max_length=16, verbose_name='Situação')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_assignments', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='private_area.monthlyschedule')),
            ],
            options={
                'verbose_name': 'Convocação',
                'verbose_name_plural': 'Convocações',
                'ordering': ['starts_at', 'function'],
            },
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='private_area.scheduleassignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_substitutions', to=settings.AUTH_USER_MODEL)),
                ('replaced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced_on_assignments', to=settings.AUTH_USER_MODEL)),
                ('substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituting_on_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Substituição',
                'verbose_name_plural': 'Substituições',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='monthlyschedule',
            constraint=models.UniqueConstraint(fields=('ministry', 'year', 'month'), name='unique_ministry_month_schedule'),
        ),
    ]
