# Generated by Django 5.2.17 on 2026-08-20 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_area', '0003_monthlyschedule_scheduleassignment_substitution_and_more'),
        ('public', '0008_pix_and_social_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Planejamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_event_operations', to=settings.AUTH_USER_MODEL)),
                ('public_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='public.eventpage', verbose_name='Evento da agenda')),
            ],
            options={
                'verbose_name': 'Operação de evento',
                'verbose_name_plural': 'Operações de eventos',
                'ordering': ['public_event__starts_at'],
            },
        ),
    ]
