# Generated by Django 5.2.17 on 2026-08-20 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_area', '0004_eventoperation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Equipe')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='private_area.eventoperation')),
            ],
            options={
                'verbose_name': 'Equipe do evento',
                'verbose_name_plural': 'Equipes do evento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='private_area.eventteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro da equipe',
                'verbose_name_plural': 'Membros da equipe',
                'ordering': ['user__username'],
                'constraints': [models.UniqueConstraint(fields=('team', 'user'), name='unique_event_team_member')],
            },
        ),
    ]
