# Generated by Django 5.2.17 on 2026-08-20 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_area', '0005_event_teams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Item')),
                ('done', models.BooleanField(default=False, verbose_name='Concluído')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_checklist_items', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='private_area.eventoperation')),
            ],
            options={
                'verbose_name': 'Item de checklist',
                'verbose_name_plural': 'Itens de checklist',
                'ordering': ['done', 'label'],
            },
        ),
        migrations.CreateModel(
            name='EventTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tarefa')),
                ('done', models.BooleanField(default=False, verbose_name='Concluída')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='private_area.eventoperation')),
            ],
            options={
                'verbose_name': 'Tarefa do evento',
                'verbose_name_plural': 'Tarefas do evento',
                'ordering': ['done', 'title'],
            },
        ),
    ]
