# Generated by Django 5.2.17 on 2026-08-20 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_area', '0006_event_tasks_checklists'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Material')),
                ('quantity', models.CharField(blank=True, default='', max_length=40, verbose_name='Quantidade')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='private_area.eventoperation')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Fornecedor')),
                ('contact', models.CharField(blank=True, default='', max_length=120, verbose_name='Contato')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='private_area.eventoperation')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
            },
        ),
    ]
