# Generated by Django 5.2.17 on 2026-08-20 04:14

import apps.private_area.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_area', '0008_event_budget_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoperation',
            name='final_report',
            field=models.TextField(blank=True, default='', verbose_name='Relatório final'),
        ),
        migrations.CreateModel(
            name='EventOperationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('file', models.FileField(storage=apps.private_area.storage.private_document_storage, upload_to='event-operations/', verbose_name='Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_event_operation_documents', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='private_area.eventoperation')),
            ],
            options={
                'verbose_name': 'Documento da operação',
                'verbose_name_plural': 'Documentos da operação',
                'ordering': ['-created_at'],
            },
        ),
    ]
