# Generated by Django 5.2.17 on 2026-08-22 04:18

import apps.private_area.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_area', '0009_event_report_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=16, verbose_name='Situação')),
                ('key', models.CharField(blank=True, default='', max_length=20, verbose_name='Tom')),
                ('tempo', models.CharField(blank=True, default='', max_length=40, verbose_name='Andamento')),
                ('lyrics', models.TextField(blank=True, default='', verbose_name='Letra')),
                ('chords', models.TextField(blank=True, default='', verbose_name='Cifra')),
                ('tags', models.CharField(blank=True, default='', max_length=200, verbose_name='Tags')),
                ('authors', models.CharField(max_length=200, verbose_name='Autoria')),
                ('source', models.CharField(max_length=200, verbose_name='Fonte')),
                ('license', models.TextField(verbose_name='Licença / autorização')),
                ('permitted_uses', models.TextField(verbose_name='Usos permitidos')),
                ('authorized', models.BooleanField(default=False, verbose_name='Há autorização para armazenar este louvor')),
                ('score', models.FileField(blank=True, storage=apps.private_area.storage.private_document_storage, upload_to='songbook/', verbose_name='Partitura PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Louvor',
                'verbose_name_plural': 'Louvores',
                'ordering': ['title'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(authorized=True),
                        name='song_requires_authorization',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='SongReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='Rótulo')),
                ('token', models.CharField(editable=False, max_length=32, unique=True)),
                ('target_url', models.URLField(verbose_name='URL externa')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='private_area.song')),
            ],
            options={
                'verbose_name': 'Referência externa',
                'verbose_name_plural': 'Referências externas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SongVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Versão')),
                ('key', models.CharField(blank=True, default='', max_length=20, verbose_name='Tom')),
                ('lyrics', models.TextField(blank=True, default='', verbose_name='Letra')),
                ('chords', models.TextField(blank=True, default='', verbose_name='Cifra')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='private_area.song')),
            ],
            options={
                'verbose_name': 'Versão',
                'verbose_name_plural': 'Versões',
                'ordering': ['id'],
            },
        ),
    ]
