# Generated by Django 5.2.17 on 2026-08-22 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_area', '0010_songbook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('service', 'Culto'), ('rehearsal', 'Ensaio')], max_length=16, verbose_name='Tipo')),
                ('starts_at', models.DateTimeField(verbose_name='Data e horário')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_playlists', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='private_area.ministry')),
            ],
            options={
                'verbose_name': 'Playlist semanal',
                'verbose_name_plural': 'Playlists semanais',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Ordem')),
                ('key', models.CharField(blank=True, default='', max_length=20, verbose_name='Tom')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='private_area.song')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_items', to='private_area.songversion', verbose_name='Versão')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='private_area.weeklyplaylist')),
            ],
            options={
                'verbose_name': 'Item da playlist',
                'verbose_name_plural': 'Itens da playlist',
                'ordering': ['position', 'id'],
            },
        ),
    ]
