# Generated by Django 5.2.17 on 2026-10-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("private_area", "0012_ministry_uses_repertoire"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtask",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Descrição"),
        ),
        migrations.AddField(
            model_name="eventtask",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Prazo"),
        ),
    ]
