from django.urls import path

from apps.private_area import event_views, ministry_views, retreat_views, views

app_name = "private_area"

urlpatterns = [
    path("area-privada/", views.home, name="home"),
    path("area-privada/documentos/", views.document_library, name="document_library"),
    path(
        "area-privada/documentos/novo/",
        views.document_upload,
        name="document_upload",
    ),
    path(
        "area-privada/documentos/<int:pk>/",
        views.document_download,
        name="document_download",
    ),
    path("area-privada/ministerios/", ministry_views.ministry_list, name="ministry_list"),
    path(
        "area-privada/ministerios/novo/",
        ministry_views.ministry_create,
        name="ministry_create",
    ),
    path(
        "area-privada/ministerios/<int:pk>/",
        ministry_views.ministry_detail,
        name="ministry_detail",
    ),
    path(
        "area-privada/ministerios/<int:pk>/escalas/nova/",
        ministry_views.schedule_create,
        name="schedule_create",
    ),
    path(
        "area-privada/escalas/<int:pk>/",
        ministry_views.schedule_detail,
        name="schedule_detail",
    ),
    path(
        "area-privada/escalas/<int:pk>/convocar/",
        ministry_views.assignment_add,
        name="assignment_add",
    ),
    path(
        "area-privada/escalas/<int:pk>/calendario/",
        ministry_views.schedule_calendar,
        name="schedule_calendar",
    ),
    path(
        "area-privada/escalas/<int:pk>/imprimir/",
        ministry_views.schedule_print,
        name="schedule_print",
    ),
    path(
        "area-privada/convocacoes/<int:pk>/",
        ministry_views.assignment_respond,
        name="assignment_respond",
    ),
    path(
        "area-privada/convocacoes/<int:pk>/substituir/",
        ministry_views.assignment_substitute,
        name="assignment_substitute",
    ),
    path(
        "area-privada/eventos/",
        event_views.event_calendar,
        name="event_calendar",
    ),
    path(
        "area-privada/eventos/novo/",
        event_views.event_operation_create,
        name="event_operation_create",
    ),
    path(
        "area-privada/eventos/<int:pk>/",
        event_views.event_operation_detail,
        name="event_operation_detail",
    ),
    path(
        "area-privada/eventos/<int:pk>/planejamento/",
        event_views.event_planning_update,
        name="event_planning_update",
    ),
    path(
        "area-privada/eventos/<int:pk>/equipe/",
        event_views.event_team_add,
        name="event_team_add",
    ),
    path(
        "area-privada/equipes/<int:pk>/membro/",
        event_views.event_team_member_add,
        name="event_team_member_add",
    ),
    path(
        "area-privada/eventos/<int:pk>/tarefa/",
        event_views.event_task_add,
        name="event_task_add",
    ),
    path(
        "area-privada/tarefas/<int:pk>/",
        event_views.event_task_update,
        name="event_task_update",
    ),
    path(
        "area-privada/eventos/<int:pk>/checklist/",
        event_views.event_checklist_add,
        name="event_checklist_add",
    ),
    path(
        "area-privada/checklist/<int:pk>/",
        event_views.event_checklist_update,
        name="event_checklist_update",
    ),
    path(
        "area-privada/eventos/<int:pk>/fornecedor/",
        event_views.event_supplier_add,
        name="event_supplier_add",
    ),
    path(
        "area-privada/eventos/<int:pk>/material/",
        event_views.event_material_add,
        name="event_material_add",
    ),
    path(
        "area-privada/eventos/<int:pk>/orcamento/",
        event_views.event_budget_add,
        name="event_budget_add",
    ),
    path(
        "area-privada/orcamento/<int:pk>/",
        event_views.event_budget_review,
        name="event_budget_review",
    ),
    path(
        "area-privada/eventos/<int:pk>/comunicar/",
        event_views.event_registrant_message,
        name="event_registrant_message",
    ),
    path(
        "area-privada/eventos/<int:pk>/relatorio/",
        event_views.event_final_report,
        name="event_final_report",
    ),
    path(
        "area-privada/eventos/<int:pk>/documento/",
        event_views.event_document_upload,
        name="event_document_upload",
    ),
    path(
        "area-privada/eventos/documentos/<int:pk>/",
        event_views.event_document_download,
        name="event_document_download",
    ),
    path(
        "area-privada/eventos/<int:pk>/retiro/",
        retreat_views.retreat_roster,
        name="retreat_roster",
    ),
    path(
        "area-privada/inscricoes/<int:pk>/pix/",
        retreat_views.retreat_pix_status,
        name="retreat_pix_status",
    ),
    path(
        "area-privada/inscricoes/<int:pk>/check-in/",
        retreat_views.retreat_check_in,
        name="retreat_check_in",
    ),
    path(
        "area-privada/familiares/<int:pk>/check-in/",
        retreat_views.retreat_member_check_in,
        name="retreat_member_check_in",
    ),
]
